[project]
name = "chess-transformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chess>=1.11.2",
    "ipykernel>=7.0.1",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
]
